import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ul>
        <li>
          <Link href="/Ecommerce">
            <a>e-Commerce</a>
          </Link>
        </li>
        <li>
          <Link href="/Inward">
            <a>Inward</a>
          </Link>
        </li>
      </ul>

      <section>
        <h1>Hello world!</h1>
      </section>
    </div>
  )
}
